### ISSUE TITLE
vulcan: Incorrect validation of numbers 

### ISSUE THREAD

**Issue by petrosagg** [g0d/micro-MVC#3]
thanks for fixing my previous issue but I think the library is still getting some outputs wrong.

For example:
```javascript
var my_vulcan = new vulcan();
var arr = [[]];
console.log(my_vulcan.validation.numerics.is_number(arr)); // prints true
```

**Comment by g0d** [comment]
According to ECMA 2015 there is indeed a series of insufficient cases about NaN.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN

I will iterate through the array and make sure that no nullable 1 index arrays exists to solve this for good.

Thanks!

**Comment by g0d** [comment]
It seems that there is no way around this after all as the IsNaN and array are too poorly implemented. The prototype and the interpreter decides that [] is magically translated to 0 and so on...

**Comment by g0d** [comment]
Closing for now until a proper solution is found or left for the standard to provide a stricter definition.

Thanks for your comment!

**Comment by petrosagg** [comment]
The ECMA standard is actually fine and the solution pretty simple. Take a look at the jQuery [implementation of isNumeric](https://github.com/jquery/jquery/blob/3.2.1/src/core.js#L222-L234) that gets it right without any iteration

**Comment by g0d** [comment]
Thanks, I will check it out and tested it out as well. Please check other parts of this library and other libs as well. Your feedback is welcome!

**Comment by g0d** [comment]
Fixed. Thanks!
