### ISSUE TITLE
Insecure storage of credentials in `auth.php`.

### ISSUE THREAD

**Issue by green-job9593** [g0d/micro-MVC#4]
Hello! I stubmled upon this project as I was looking for a PHP framework. I noticed that in the `auth.php` module the passwords as just their unsalted MD5 hash.

https://github.com/g0d/micro-MVC/blob/8ed8b2f01de1077bc21143739335bd106da73f36/framework/misc/dispatchers/gates/auth.php#L57-L58

This is insecure for many reasons: it is extremely easy to crack MD5 hashes, and leaks information in cases two users have the same password. I recommend you to consult guides such as https://crackstation.net/hashing-security.htm to learn how to securely hash passwords.

Thanks!

**Comment by g0d** [comment]
Hello you are right!

However, this is not a final solution but rather a test template as part of the module for "auth" in the framework. It is there to showcase the basic usage.

It has been noted by other fellow engineers as well, so I will updated to avoid any further misunderstandings...
